name: 16 - Working with Environments

on:
    workflow_dispatch:
        inputs:
            target-env:
                type: environment
                default: staging

                
run-name: 16 - Working with Environments | env - ${{ inputs.target-env }}


jobs: 
    deploy-staging:
        runs-on: ubuntu-latest
        environment: ${{ inputs.target-env }}  
        env:
            my-env-value: ${{ vars.MY_ENV_VALUE || 'default value' }}  
        steps:
            - name: Echo vars
              run: |
                echo "Deploying to staging" 
    e2e-tests:
        runs-on: ubunut-latets
        needs: deploy-staging
        steps:
            - name: E2E tests
              run: echo "Running E2E"
              
    deploy-prod-frontend:
        runs-on: ubunut-latest
        needs: e2e-tests
        environment: prod
        env:
            my-env-value: ${{ vars.MY_ENV_VALUE || 'default value' }}  
        steps:
            - name: Echo vars
              run: |
                echo "Deploy to frontend"

    deploy-prod-backend:
        runs-on: ubunut-latest
        needs: e2e-tests
        environment: prod
        env:
            my-env-value: ${{ vars.MY_ENV_VALUE || 'default value' }}  
        steps:
            - name: Echo vars
              run: |
                  echo "Deploy to backend"                



