name: 18 - 3 - Reusable Workflows

on:
    workflow_dispatch:
        deploy:
            uses: ./.github/workflows/18-1-reusable-workflows.yaml
            with:
                target-directory: test-dir

        e2e-tests:
            needs: deploy
            uses: jonatan-bradley/.github/workflows/e2e.yaml@main               
